name: "Deploy to dokku"

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
                  ref: master

            - name: Deploy to dokku
              uses: vitalyliber/dokku-github-action@v6.2
              env:
                  PRIVATE_KEY: ${{ secrets.SECRET }}
                  FORCE_DEPLOY: true
                  BRANCH: master
                  HOST: ${{ secrets.SERVER_IP }}
                  PROJECT: simple-proxy
